version: "3.8"

services:
  app:
    # This is your dev container (Node + TypeScript)
    image: ghcr.io/codesandbox/devcontainers/typescript-node:latest

    # Mount your project into the container
    volumes:
      - .:/workspace

    # Keep the container running for VS Code / dev tools
    command: "sleep infinity"

    # (Optional) Expose your app port, for example 3000
    ports:
      - 3000:3000

  qdrant:
    # Official Qdrant image
    image: qdrant/qdrant:latest

    # Expose Qdrant's default port
    ports:
      - 6333:6333
